### PR TITLE
Support dropping folders

### PR DESCRIPTION
**Pull request by kevinleedrum**
Happy Hacktoberfest! 🎃 

This PR adds the ability to drop folders, which will be parsed recursively for files.

Before: ☹️ 

oDMMQDjHOR

After: 😄 

e64MB8MUhg

### CODE REVIEW

**Comment by safrazik** [comment]
Thank you for the pull request. This is a very welcomed feature (that I had thought of supporting in the future). I will do some testing on my side and merge. Thanks. Happy Hacktoberfest!

**Comment by safrazik** [comment]
Hi @kevinleedrum great work. I tested it and works perfectly. My only concern is that you are using `async/await, which will result in the regeneratorRuntime being added to the dist files which in turn affect the dist file size (+`84KB` unminified, +`25KB` minified) . I have avoided using some es6+ features on purpose because I was too concerned about the file size. As this is a library.

**Comment by kevinleedrum** [comment]
Good point.  I will convert it to promises.

**Comment by kevinleedrum** [comment]
@safrazik I've replaced `async/await` with promises, and I also replaced `const` and `let` with `var` to match the rest of the project.

**Comment by safrazik** [comment]
@kevinleedrum Thank you for your work.
BTW, I don't think `const` or `let` will cause any trouble, but yeah, it's good to keep things consistent. Since the library evolved by time (before being open sourced) you will see a lot of old fashioned code. It would be better to do some code refactor in the future. Thanks for helping.

**Comment by Garito** [comment]
My two cents on that:
const, let & var have different repercussions (in that case scope & performance)
const should be used for non mutable values for performance
let & var should be used to control the scope of the variable (var being less "local")

So, I would rather prefer that kind of consistence

**Comment by safrazik** [comment]
Sure. I haven't seen a better (short) explanation than this for const and let. Thanks.

**Comment by safrazik** [comment]
@kevinleedrum Support for dropping folders landed in version 1.3 Rock Wren. Thanks for your contribution.

**Pull request merged**
